version: '3.7'
services:
  url-shortener-server:
    container_name: url-shortener-server
    environment: 
      - NODE_ENV=production
    build:
      context: ./
    image: url-shortener-server
    ports:
      - "4000:4000"